pool:
  name: builders

variables:

- template: job-variables.yml

- name: imageRepository

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_stage') }}:

    value: $(imageRepositoryStage)

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_release') }}:

    value: $(imageRepositoryRelease)

- name: imageName

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_stage') }}:

    value: $(imageNameStage)

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_release') }}:

    value: $(imageNameRelease)

- name: containerName

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_stage') }}:

    value: $(containerNameStage)

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_release') }}:

    value: $(containerNameRelease)

- name: build_arg_arguments

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_stage') }}:

    value: $(docker_build_arguments_stage)

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_release') }}:

    value: $(docker_build_arguments_release)

- name: deploymentName

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_stage') }}:

    value: $(deploymentNameStage)

  ${{ if eq(variables['Build.SourceBranchName'], 'docker_release') }}:

    value: $(deploymentNameRelease)

stages:
- stage: Docker Login
  jobs:
  - job: login  
    displayName: Login to Docker Hub 
    steps:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: containerRegistry

- stage: Docker Build backend
  jobs:
  - job: build  
    displayName: build backend image   
    steps:
      - task: Docker@2
        displayName: Build and push an image to azrue container registry
        inputs:
          containerRegistry: $(containerRegistry)
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          command: buildAndPush  
          arguments: $(build_arg_arguments)
          tags: |
            $(Build.SourceVersion)
            latest

- stage: Docker Build frontend
  jobs:
  - job: build  
    displayName: build frontend image   
    steps:
      - task: Docker@2
        displayName: Build and push an image to azrue container registry
        inputs:
          containerRegistry: $(containerRegistry)
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          command: buildAndPush  
          arguments: $(build_arg_arguments)
          tags: |
            $(Build.SourceVersion)
            latest
            