apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-python
spec:
  selector:
    matchLabels:
      app: backend-python
  replicas: 4
  template:
    metadata:
      labels:
        app: backend-python
    spec:
      containers:
      - name: backend-python
        image: backend-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000